# Generated by Django 4.1.7 on 2023-05-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=100)),
                ('image_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('sequence_id', models.CharField(max_length=100)),
                ('tag', models.IntegerField()),
            ],
        ),
    ]
