# Generated by Django 4.1.7 on 2023-05-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='author',
            field=models.CharField(default='dina', max_length=20),
            preserve_default=False,
        ),
    ]
