# Generated by Django 4.1.7 on 2023-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_id', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
            ],
        ),
    ]
