# Generated by Django 4.1.7 on 2023-05-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
