# Generated by Django 4.1.7 on 2023-05-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
