# Generated by Django 4.1.7 on 2023-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_sequence_id_sequence_images_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.AddField(
            model_name='reviewedsequence',
            name='selections',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
