# Generated by Django 4.1.7 on 2023-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_delete_sequence_reviewedsequence_selections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewedsequence',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.AddField(
            model_name='reviewedsequence',
            name='frame_00',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
