# Generated by Django 4.1.7 on 2023-07-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_reviewedsequence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewedsequence',
            name='length',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
